// Generated by CoffeeScript 1.7.1
(function() {
  var names;

  names = {};

  names.hometown = {
    gd: '广东',
    zj: '浙江',
    cq: '重庆',
    ah: '安徽',
    sx: '陕西',
    hb: '河北'
  };

  names.college = {
    bupt: '北邮',
    bit: '北理工',
    sysu: '中大'
  };

  names.hobby = {
    'foosball': '桌上足球',
    'pes': '实况足球',
    'sorry': '不方便说'
  };

  names.status = {
    'not-paid': '未到款',
    'not-returned': '未还款',
    'returned': '已还款'
  };

  names.greatness = {
    'great': '伟大',
    'ordinary': '平凡',
    'hedgehog': '刺猬',
    'slag': '贱人',
    'science': '为科学献身',
    'soccer': '史诗球员',
    'fly': '飞翔着',
    'gold': '土豪金'
  };

  if (window.debtApp == null) {
    window.debtApp = {};
  }

  window.debtApp.names = names;

}).call(this);
